channels:
- conda-forge
dependencies:
- bagofholding =0.1.9
- bidict =0.23.1
- cloudpickle =3.1.2
- executorlib =1.8.0
- graphviz =9.0.0
- hatchling =1.28.0
- hatch-vcs =0.5.0
- pandas =3.0.0
- pint =0.25
- pyiron_snippets =1.0.2
- python >=3.11,<3.14
- python-graphviz =0.21
- rdflib =7.1.4
- semantikon =0.0.27
- toposort =1.10
- typeguard =4.4.4
