channels:
- conda-forge
dependencies:
- ipykernel
- myst-parser
- nbsphinx
- sphinx-gallery
- sphinx-rtd-theme
- coveralls
- coverage
- bidict =0.23.1
- cloudpickle =3.0.0
- graphviz =8.1.0
- h5io =0.2.2
- h5io_browser =0.0.9
- matplotlib =3.8.2
- pyiron_contrib =0.1.15
- pympipool =0.7.13
- python-graphviz =0.20.1
- toposort =1.10
- typeguard =4.1.5
